# Generated by Django 4.0.6 on 2022-07-21 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0003_entrable_profesor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrable',
            new_name='Entregable',
        ),
    ]
